server:
  port: 8765
  servlet:
    context-path: /api
spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:postgresql://localhost:5432/StdManage}
    username: ${DBMS_USERNAME:postgres}
    password: ${DBMS_PASSWORD:giabao123123}
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 60000
  jpa:
    hibernate:
      ddl-auto: none # Hoặc create, create-drop, validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
